### ISSUE TITLE
Abble to use FOV change in camerapath

### ISSUE THREAD

**Issue by ztaborosi** [Snow1226/CameraPlus#10]
Hi,
It is rather an idea than a bug:
Is it possible to add a fov value too to the camerapath.cfg?
This would allow us to use it for fancy camera moves+fov changes.

Regards,

**Comment by Snow1226** [comment]
There is a FOV in both cfg and movescript.
What do you want?

**Comment by ztaborosi** [comment]
Hi,
There is non in the example cfg. however i will try it out adding fov into the json string later.
thanks.

**Comment by Snow1226** [comment]
Isn't camerapath.cfg a file you created?
This file is not generated by cameraplus.
Isn't it another mod?
