### ISSUE TITLE
mod turning off by itself

### ISSUE THREAD

**Issue by nelsonjmorris** [Snow1226/CameraPlus#14]
idk if this makes sense or not. i use a quest 2 with link and whenever it senses my head the cameraplus mod switches to normal in game camera settings (the shaky camera), but when it doesnt detect my head, cameraplus resets to the settings i set it to.

**Comment by Snow1226** [comment]
It's a specification.
With the update of the Unity version of the game itself, it became such a specification.

**Comment by Snow1226** [comment]
Also, since the specifications are the same on the Oculus side,
Link disconnection cannot be handled on the cam + side.
If it is cam2, it may be okay because it is generated by another approach.
