### ISSUE TITLE
About MovementScript

### ISSUE THREAD

**Issue by chika999** [Snow1226/CameraPlus#15]
When I use “Tick UnityTimer” mode，just start playing a song，my movement script will move from the first coordinate，It was normal before.

I'm not sure if you can understand what I'm describing, because I use Google translation. Please forgive me for my poor English.

**Comment by chika999** [comment]
This is a video I recorded before. When I start playing a song, the script will continue to move in its current position instead of the whole script running again.

https://www.bilibili.com/video/BV1yp4y1H7uZ

**Comment by Snow1226** [comment]
Thanks for the report.
Don't worry, I'm using a translation here too.
I think it's probably the part I modified for AudioSync that's causing the problem.
Please wait for me to check.

**Comment by chika999** [comment]
Thank you for fixing it! I have just updated version 5.1.0, and confirm that it has returned to normal. Thank you again! 😃
