### ISSUE TITLE
Cannot get 6.2.0 version to start with BS 1.19.0 version

### ISSUE THREAD

**Issue by MikkArt** [Snow1226/CameraPlus#19]
I uninstalled BS deleted old folders. Made new fresh install and started once BS. Then unpacked the zip to folder where Beat saber exe file is. Started game tried right clicking get no cameraplus. Tried copying from within CameraPlus-6.2.0 folder all files to Beatsaber folder with beat saber exe. Also tried unpacking and copying the Beatsaber.dll to Plugins folder. Camera plus does not open on monitor with right click. Have been using Camera plus for long time without issues before this issue with 6.2.0

**Comment by Snow1226** [comment]
If you delete all the folders
There will be no BSIPA to load mods.
In other words, CameraPlus itself is not loaded.
BSIPA is required to run Camera Plus.
Please install BSIPA 4.2.0 for 1.18.3 or wait for the Mod Assistant update.
