### ISSUE TITLE
Lagspikes when used in conjunction with Gotta go fast

### ISSUE THREAD

**Issue by kinsi55** [Snow1226/CameraPlus#7]
Hey,

I've created the afformentioned mod [gotta go fast](https://github.com/kinsi55/CS_BeatSaber_GottaGoFast) and seemingly at random *some* people reported to me that they get 2 lag spikes in the beginning of songs (Which can make some songs hard to play which start in the time period where the lag spikes happen), but only when they *restart* a song, if they just normally start a song they dont have it.

Since restarting a song does a scene transition to the menu and into the song again I assumed the issue has to be related to some mod that does some (probably unnecessary because they dont check if its a song restart) processing for the hidden menu transition. Having done some trial and error debugging, that mod seems to be Camera+ - 2/2 people who I've asked so far to test if removing camera plus removes the lag spikes said that it does.

I tried to do some basic debuggin with cam+ where I (If my code was correct that is) skipped the `DelayedActiveSceneChanged` implementation if the `to` scene isnt the most recent one that reached `OnActiveSceneChanged` but that did not seem to resolve the issue.

I understand that this might very well be something not in your interest to look into since the lag spikes normally fall into loading time, but maybe you have an idea what it could be caused by and would possibly like to resolve it anyways? :)

Thanks in advance

**Comment by Snow1226** [comment]
It is probably the cullingmask process of cam+.
This is the part where the culling process is done after the scene transition is stabilized.
This is because the cullingmask of the game is different between the menu scene and the game scene since the game version 1.8.0.
You need to switch the culling for cam+ that is displayed across both scenes.
If the culling process is brought forward, a CRITICAL error will occur at irregular intervals, and this is already a specification because it is more likely to occur for people with lower PC specs.

**Comment by kinsi55** [comment]
Would it be possible then to skip this process when you're restarting a song? In that case the cameras can just keep their culling mask and reuse it, right?

**Comment by Snow1226** [comment]
So you're pausing and restarting GameCore?
If so, that's different...
It pauses and resumes the movescript, but I don't think it does anything else.

**Comment by kinsi55** [comment]
No, my plugin does not modify the original flow of actions, but when restarting a song the game ofc goes back to the menu and then automatically starts the song again, hence me wondering it it would be possible to skip initialization of the menu cameras in that case and just keep reusing the previous gamecore ones so they don't need to be recreated

**Comment by Snow1226** [comment]
I'm not a native English speaker, so it's a little difficult to understand.
Would it be possible to rework the mod flow itself?
I'll consider it, but I don't have any skills beyond maintenance, so I think it will be difficult.

**Comment by kinsi55** [comment]
Ok I understand, I will go a bit more into detail:

When you restart a song what happens in the background is that the game will go back to the menu, like you pressed the menu instead of the restart button, but once it is in the menu it will automatically start the same song again - you never see the menu but it is loaded. This is obviously one of the reasons restarting a song is so slow by default.

By default this does of course not cause any issues because the song restart takes like 2-3 seconds so most mods (Including camera+) are done doing all of the stuff that they tried to process / load from going back to the menu, but with my mod the song restart time goes down to about half a second or less.

In the restart process Camera+ will of course follow the game flow and initialize the cameras for the main menu (Which is never seen) only to initialize them for the game scene again afterwards. What I was wondering is if it would help to know in advance that the scene switch away from the game scene is for the purpose of restarting a song, and in that case ignore it and make Camera+ hold onto the created cameras so that it does not need to do any heavy processing on the restart of a song.

**Comment by Snow1226** [comment]
Restarting a song is when you stop the game you are playing and press Restart?
Well, I'll think about it, but don't hold your breath.
I also use DeepL.
The conversion to Japanese is basically difficult.

**Comment by kinsi55** [comment]
> Restarting a song is when you stop the game you are playing and press Restart?

Correct, that is what I mean.

I will try to do some changes to Camera+ myself and see if anything works, if so I will let you know. Thank you for the consideration.

**Comment by Snow1226** [comment]
I understand. Thank you very much.

**Comment by kinsi55** [comment]
Alright I've done a lot of back and forth testing, this is what my code is right now. I would absolutely not consider it to be ready to ship *but* from my limited testing, at least basic camera+ usage still works completely fine, and most importantly, the lag spikes seem to be gone entirely.

https://github.com/kinsi55/CameraPlus/commit/9a55e0a94702508449041654154525e5770d554b

**Comment by Snow1226** [comment]
Thanks for the sample code.
I've tried it, but
It looks like it's working, but the scene itself is reloaded and the CullingMask is initialized.
So if I skip the culling process, it does not display as intended.😣

**Comment by kinsi55** [comment]
Okay, I have another Idea, I will implement it a little bit later.

**Comment by kinsi55** [comment]
I've implemented my idea now, seems like the culling mask was not even the issue. The way it is implemented now it sets the culling mask when going into the song again and still does not lag.

I had implemented it differently at first (commented code) where using some memory hacks I stubbed out the original mask setter, allowing to keep the previous mask, but that is unsafe code and apparently not really necessary so I removed it again.

**Comment by Snow1226** [comment]
Thanks, I've tried it and Culling looks good, but the Noodle Extensions PlayerTrack tracking stops working.
For example, this
https://beatsaver.com/beatmap/11cf8

I'll give this some thought.

**Comment by kinsi55** [comment]
I see, well you get the general idea.

I'm assuming your latest commit is not complete but you should definitely consider implementing all of the changes I made to the `DelayedActiveSceneChanged` (Mainly the [different method of waiting for Camera.main](https://github.com/kinsi55/CameraPlus/blob/master/CameraPlus/Plugin.cs#L147)) as well as the [processing bypass](https://github.com/kinsi55/CameraPlus/blob/master/CameraPlus/Plugin.cs#L113-L135) I implemented when restarting a song as they are also significant factors to decreasing the stutters.

**Comment by Snow1226** [comment]
Except for the process bypass, I plan to adopt it because it works to shorten the process.
Only the process bypass is troubling me.
If I bypass it, the link to the origin point where NoodleExtensions is running will be broken.
I'd like to reset it somehow, but due to the use of transform.parent I can't get it to work except for the camera reset.

**Comment by kinsi55** [comment]
If the only issue with my implementation is that your Noodle implementation is broken I will try to find a solution for that, I'll let you know once I have one.

**Comment by kinsi55** [comment]
I tried around a bit, I'm having a lot of issues even understanding how the control flow in camera plus works and everything seems very spaghetti code to be honest, but, the code in my repo now works with your noodle function.

**Comment by Snow1226** [comment]
Thanks, I'll check it out after work.
I agree about the rebuild, though my skills are lacking.

But there are a lot of restrictions because the update policy is not to rely on anything other than BSIPA.
For example, even if CoreMod is late in updating, as it was in game 1.12.0, streamers can still make screens as long as they have a camera.

**Comment by kinsi55** [comment]
I would rather make it a completely new plugin instead of an update if you were to rewrite it. If you wanted to make it an update, I *think* if you released it as a new major version (So V5.0) you should be able to depend on new things, but I am not exactly sure how Beatmods handles that.

**Comment by Snow1226** [comment]
I've tried.
I was getting the following error as to why I had originally added WaitForSeconds.
Again, when I shorten it, it occurs irregularly.

[ERROR @ 21:13:40 | CameraPlus] Exception cameras culling! Exception: Object reference not set to an instance of an object
[ERROR @ 21:13:40 | CameraPlus]   at CameraPlus.CameraPlusBehaviour.SetCullingMask () [0x000e6] in <ad89f8f4a4414d66a93c1ca067917a0e>:0 
[ERROR @ 21:13:40 | CameraPlus]   at CameraPlus.CameraUtilities.SetAllCameraCulling () [0x00019] in <ad89f8f4a4414d66a93c1ca067917a0e>:0 

Also, on the development PC, the NoodleExtensions tracking seemed to be working but, on a stream PC, it sometimes didn't work even in the first play without restarting.😢

**Comment by Snow1226** [comment]
I'll still check it out, but...
Maybe I can set it to skip only when I have GottaGoFast.🤔

**Comment by kinsi55** [comment]
While you probably could, tackling an issue like this with random number delays is very ugly hence me trying to look for a solution that does not need it

**Comment by kinsi55** [comment]
Out of curiousity, in your system where it does not work, are you using the profile switcher?

**Comment by Snow1226** [comment]
I tested it by streaming for two hours. Everything was resolved, so I'd like to make a decision on this branch.
Thank you for your cooperation.🎉
