### ISSUE TITLE
CameraMovement Script does not work.

### ISSUE THREAD

**Issue by ztaborosi** [Snow1226/CameraPlus#8]
-It loads the json files from the folder
-It updates the cameraplus.cfg
-The camera moovement does not happen .. neither during song nor in the menu nor in the pause state.
-Confirmed working in 4.4.2 (but the game crashes obviously)

**Comment by Snow1226** [comment]
Sorry for the delay in adding it to the readme.
Would the following information help?

https://github.com/Snow1226/CameraPlus/issues/6

**Comment by ztaborosi** [comment]
Hi,
I saw that issue but i excluded as the older version works fine.. i will check later today...ty

**Comment by ztaborosi** [comment]
Hi, yes. it solved.
Damn these localization stuff.

Thank you

**Comment by Snow1226** [comment]
Thanks for the report!
I think the reason for the outbreak is that I left the library to BSIPA in 4.5.0.
I'll see if I can't absorb the localization.
